runtime: nodejs16
service: api

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

skip_files:
  - .github/
  - .husky/
  - .vscode/
  - test/
  - .env.example
  - .eslintignore
  - .eslintrc.js
  - Makefile
  - jest.config.js
